### ISSUE TITLE
implementation of mucbin

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#127]
"exact" calculation of the mean of cbinom(size, prob) is very computationally intensive and not readily vectorizable. We only need to calculate it for the special case where M = 1/g, making it a one-dimensional problem. E[cbinom(1/g, g)] is a well-behaved function in the sense of being smooth and monotone with no sharp bends---so can be readily approximated via linear interpolation. 

R's approxfun(x, y) returns a fast, vectorized function for interpolation, e.g.,
mucbin <- approxfun(g_val, Ecbin_val), where g_val is a vector of values spanning [0, 1] + epsilon*c(-1, 1) and Ecbin_val is the corresponding array of "exact" values of the mean.  Usage would be mucbin(g), returning the expected value of x for prob = g and size = 1/g.

The function can then be compiled and incorporated into the package as "data" as follows:

```
require(cbinom)
g <- c(0.0001261, 0.99999)
mug <- numeric(2)
for (gi in 1:length(g)){
  mug[gi] <- integrate(function(x, size, prob) 1 - cbinom::pcbinom(x, size, prob), size = 1/g[gi], prob = g[gi], lower = 0, upper = 1/g[gi] + 1 - .Machine$double.eps)$val
}
y <- seq(min(mug), max(mug), length = 200) # 0 and 1 will be appended at the end
gkey <- numeric(length(y))
for (yi in 1:length(y)){
  gkey[yi] <- uniroot(f = function(prob){
      integrate(function(x) 1 - cbinom::pcbinom(x, 1/prob, prob), lower = 0, upper = 1/prob + 1)$val - y[yi]
    }, lower = 0.00012609, upper = 1 - .Machine$double.eps)$root
}
gkey <- c(0, gkey, 1)
Ecbin <- c(1.48204, y, 2)
mucbin <- approxfun(x = gkey, y = Ecbin)
devtools::use_data(mucbin)
```
After building into the app and installing, the function is available for use.

**Comment by ddalthorp** [comment]
maybe even better than use_data(mucbin) would be: `use_data(mucbin, internal = T)` since it probably isn't worth exporting this little guy at all...might as well tuck it away, wholly out of view (except to the persistent and determined curious).

**Comment by DAPPERstats** [comment]
is there a benefit or need to setting this up as data rather than its own function? (to keep it inline with the other functions and to set up documentation easily and such, although we could also document it like the datasets, but then it would be marked as a dataset rather than a function.

**Comment by ddalthorp** [comment]
It doesn't function like ordinary functions and I'm not sure how to set it up like other functions. Importing it as internal data, though, is easy. Its flavor is very much like Hadley's description of internal data. Also, it's a great candidate for not exporting, so the documentation could be limited to annotated code in `data-raw/`

**Comment by DAPPERstats** [comment]
totally on the data underlying the interpolation being pretty much exactly Hadley's internal data description.

in making sure I understood what this code was doing, I reorganized it a bit and found a pretty clean way to generalize the function that gets called in the code, while having the underlying data used not need to be generated de novo (the goal of putting it in internal data). the approach leverages that internal data are available to functions, just not users, so basically I wrote a wrapper around the 

```
mucbin <- approxfun(x = gkey, y = y)
```
that only takes `prob` as an argument, and pulls the x and y values in from the internal data object I created. 

I've got code up and running that produces identical results in virtually the same amount of time (accessing the data object actually takes like 0.001-0.01 seconds) and will include it in the next pull request with associated "downstream of ghat" code.

It includes a new script `/data-raw/mucbinomxy` that creates the data file, the data file (`/R/sysdata.rda`, which contains a single object: `mucbinomxy` that has two elements, `x` and `y`), and then the user-available function `mucbinom` that is the wrapper I mentioned above.

Given that this code is actually generalized and likely of utility to others, this functionality might be better located in the `cbinom` package at some point, but it's totally fine living here for now. If you do move it over there, I would definitely think about bringing the data-table generation into the `mucbinom` function itself (rather than having the function call the internal data, or maybe setting up the function to be flexible to do it either way), as the resolution used obviously impacts the estimate and users may way a resolution different than we used here.

**Comment by DAPPERstats** [comment]
brought in now w v 0.0.3.17 (I was playing with some code, so its PRs #131 #130 #129 ). check it out and let me know what you think.

**Comment by ddalthorp** [comment]
OK!

The function is too obscure to worry about for cbinom package...it only works if need to calculate the mean millions of times when you have size = 1/g and prob = g. Outside of our newly invented model, I don't think the function would ever get used. If it were generalized to work with arbitrary size, it might find some utility, but that's not something we should be working on or thinking about right now!

**Comment by DAPPERstats** [comment]
thanks for checking this, and sorry the rearrangement broke things and made it difficult for you to follow! i'll get this integrated soon.

the main reason for pulling the function definition out to a different spot is so that it can be used outside of functions within the package, in the instance that a command-line user (us included) would like to calculate `Mtilde` using the raw equations rather than the compiled functions once the package has been built. 

by way of example, in the currently up version of the code, the `mcubinom` function is available to the user at the command line. in comparison, the three `cbinomF` functions defined out within that script are not available to call for a command line user. the ability to call the `cbinomF` functions isn't needed at all, but `mcubinom` could be quite helpful for a command line user to be able to call to troubleshoot odd output.... and it's exactly that moment where it is incredibly frustrating when the function isn't available or even located with the other function code, and thus difficult to track down. 

re: the function name, as with other object names, I'm working to integrate the new downstream code with our existing code base and the style requirements, and that sometimes has meant name changes, although that has minimized with getting on the same page re: function naming, etc.

specifically here, the reason I changed it was following the guidance under the Abbreviations section in the style guide. in particular, it was to clarify that it is the mean of `cbinom`, as the abbreviation `cbin` isn't "commonly used" (internally, this was its first appearance in the code) and is one letter shy of the very common R abbreviation `cbind`.  The combination of a previously unused abbreviation that is similar to another base R standard/common abbreviation and the "abbreviate without capitalization" rule (which otherwise works in the case that the root word is a known abbreviation) makes `mucbin` an abbreviation that has a danger of misinterpretation/is not as easily interpreted by a reader of the code. `mucbinom` was chosen instead to clarify that.

**Comment by ddalthorp** [comment]
Yeah, we should probably export mucbin---because there's a chance someone else would want to use it, but there's a certainty that Lisa and or I will want to. And we want to be using the most up-to-date GenEst version (with format compatible with our already existing research code, if possible, i.e., same name, same input format, same output format).

The best name would probably be something more like Ecbinom because "mu" is _really_ NOT the mean; we know "mu" because it is a familiar parameter in the normal distribution that just happens to be the expected value (E). But, if we changed it, then next week we might decide that some other name is even more better. Maybe the quest for the perfect name is a bit of a rabbit trail?

**Comment by DAPPERstats** [comment]
if `Ecbinom` is a better name (which I agree with) than `mucbinom`, then let's go with that.
the potential for there to be a better name for a function at some point down the line is certainly non-0, but i think that's a bit of a straw argument... that we can improve on something further down the line shouldn't prevent us from improving on things now, otherwise we'd never get anywhere.

**Comment by ddalthorp** [comment]
OK. Let's do it. 

I'll do a search-and-replace in all my mucbin'd files as needed.
