### ISSUE TITLE
sampling fraction

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#151]
We need a button in fatality estimation tab asking for sampling fraction (e.g., fraction of turbines sampled). The adjustment for sampling fraction (f) is similar to the other adjustments.

(1) Either carcass-wise:
`((rcbinom(length(ghat), 1/(ghat * dwp * f), ghat * dwp * f)) - (Ecbinom(ghat * dwp * f) - 1))/(ghat * dwp * f)
`
(2) Or after calculating splits: Mhat1, Mhat2, Mhat3, ...
`((rcbinom(length(ghat), Mhat1/f,  f) - 0.5)/f` <-- IF Mhat1 > 10 or so; otherwise:

`(rcbinom(length(ghat), Mhat1/f,  f) - (integrate( 1- pbeta(...))$val - Mhat1))/f `<-- IF 0 < Mhat1 <= 10 and the pbeta is as described in the help file for pcbinom; otherwise:  do carcasswise calculation.

Solution (1) is much slower than (2) but easier to implement. They will be comparable in terms of accuracy. Let's go with (1) for now and switch to (2) only if we run into speed issues (or something unforeseen comes up). (1) has a nice aesthetic of fitting in so well with the other adjustments.

**Comment by DAPPERstats** [comment]
i think i misunderstood the application of `DWP` and then also `f` under the new `M` estimation procedure. 

i had basically just been doing a straight up division of the carcass-specific `Mtilde` values by the carcass-specific `DWP` values and was planning to implement `f` the same way

but what it looks to me like now (finally getting it?) is that both `DWP` and `f` are included in the `Mtilde` (and `Xtilde`) calculations?

this means then that there's really not a distinction between `Mtilde` and `Mhat` in the way there was before, right? (rather than `Mtilde` being `Mhat` before the `DWP` correction, now we can generate `Mtilde` and `Mhat` values by using the same equation (what was before for `Mtilde`) now with `DWP` either set to 1 or not. [this tables the point about whether it's still `Mtilde` given that `f` is included]

**Comment by ddalthorp** [comment]
Yeah, if we just divide by dwp and f, we miss the binomial uncertainty and underestimate the variance of Mhat. Including dwp and f in the xtilde calculation is more accurate (in terms of coverage...the means are the same whether you divide before or after xtilde). 

I was envisioning a hierarchy of estimates of M, each encompassing another layer of extrapolation (most notably, dwp and f). Paul disabused me of the notion that that'd be a good idea. And Manuela concurred. So we will just do one Mhat, as: 

sum(rcbinom(1/(g * dwp * f), g * dwp * f) - (Ecbinom(g * dwp * f) - 1))/(g * dwp * f) 

at the end.

**Comment by DAPPERstats** [comment]
got it!
yeah, that totally makes more sense now that i think about it
thanks for clarifying, and sorry it hadn't clicked yet.

**Comment by ddalthorp** [comment]
I don't.

**Comment by DAPPERstats** [comment]
included as of v 0.0.6.1 and beyond (esp 0.0.6.4) #206 #212
