### ISSUE TITLE
ERROR: there is no package called ‘shinydashboard’

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#153]
I could not get 0.0.5.5 to run...without installing "shinydashboard" first by hand

**Comment by DAPPERstats** [comment]
so it looks like this is part and parcel of installing from local binaries...the dependencies don't get installed, even when you pull a zip file down from CRAN. (In digging into this, on the help page for `utils::install.packages` it says dependencies aren't downloaded if `repos = NULL`, which is the condition needed for local-file installation. 

`devtools::install_github()` was circumventing this issue, but now that we're avoiding that approach due to the need to install Rtools, we need another approach.

there's a handy `devtools::install_deps()` function that does all of the handling of installing dependencies, but it needs to be pointed to the unzipped version of the package, so there will need to be some additional hand-holding for installation (instructions to unzip the folder and to point to it within R), which is a bit frustrating

the other option is, given that we know what the dependencies are, we can just give folks a line of code that runs `install::packages()` with all of the required files

so right now, i see three options:
[1] use `devtools::install_github()`, which requires Rtools to be installed, which is not optimal, but the installation of the package itself is then super-clean
[2] provide the source files for folks to install from, give them a line of code that then also installs dependencies in R
[3] provide the source files for folks to install from, give them instructions to unzip the folder, point R to it, and use `devtools::install_deps()`

The simplest approach at this point is probably 2, but let me know if you have other ideas on this issue

**Comment by DAPPERstats** [comment]
the issue with option [2] is going to be maintaining that list, an alternative approach is

install from local folder, then run 
```
install.packages("devtools")
devtools::install_deps(paste0(.libPaths()[1], "/GenEst"))
```

**Comment by DAPPERstats** [comment]
I''ve tried this apprach (`install_deps`) on a clean computer without Rtools and it seems to work for me.

Can someone(s) try it and let me know?

Big benefit of this approach is no need to maintain that long list of dependencies, this version will automatically check what's needed for that version of the package and download it.

**Comment by ddalthorp** [comment]
Great work getting this nailed down.

The long-term solution will be CRAN.

The simplest short-term, beta review solution (for Windows users) would be:
(1) download the zip;
(2) run two lines of code to find which packages have not been installed, and then install them.

Mac and Linux should be fine with the source package at GitHub.

**Comment by ddalthorp** [comment]
In your solution [2] do you mean the Windows binaries rather than source? Can the thing be compiled without setting up Rtools?

**Comment by DAPPERstats** [comment]
yes sorry, binaries not source. 

and yeah this is just in the short-term before a stable version gets up on CRAN, so we don't need the best-ever solution, just something that's simple for beta users to implement.

**Comment by ddalthorp** [comment]
When we get the temp review hosting finalized, we can put an appropriate temp solution up there...either your devtools::install_deps (which requires devtools but not an explicit list of packages) or something like the following (which requires the specific list of packages but not devtools):
```
req.pkg <- c("shiny", "gsl", "cbinom", etc.)
install.packages(req.pkg[!(req.pkg %in% installed.packages())])
```

**Comment by DAPPERstats** [comment]
i think we have a good working set up now in the readme as of v 0.0.5.7 #157
