### ISSUE TITLE
calcSplits w/in app

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#161]
I've found the source of the problem...am fixing today.

**Comment by ddalthorp** [comment]
That's because it hasn't been playing nicely with app's command-line functions.

**Comment by DAPPERstats** [comment]
ok the way you wrote that made it seem like calcSplits was in the app, which it isn't yet because i haven't gotten to integrating that code yet. if you're fixing the calcSplits code to work with the other command line functions, that's great! (but it's regardless of the app, sorry that's all i was confused about)

**Comment by DAPPERstats** [comment]
did the edits you made yesterday/today address this issue or are there still things lingering?

**Comment by ddalthorp** [comment]
everything was working fine for me last night. You found and corrected two "special case" side bars this morning. 

I believe that should do it!
