### ISSUE TITLE
generalize the factorcombinations function

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#18]
allow to work with more factor combinations
base flexibility on make_egDat function

**Comment by mhuso** [comment]
I'm not sure I follow. I think we were all agreed that two factors (with their inherent combinations) was enough. Is this an issue because 2 10-level factors will result in 100 combos that will crash the system? I don't foresee anyone doing adequate trials to be able to estimate 100 combinations. But perhaps we need to understand where our limitations lie. Is 12 or 20 too many?

**Comment by DAPPERstats** [comment]
if we're sticking with max 2 factors for each now, this isn't an issue for us to be concerned with. i'll close it for now and we can re-visit it later if we decide that we want to generalize the models to >2 factors.
