### ISSUE TITLE
Generalize CP models so that both parameters depend on covariates

### ISSUE THREAD

**Issue by prabie** [ddalthorp/GenEst#27]
I have this solved for the single covariate case & have tested it for Weibull-distributed data.  Still need to 
  1.  Ensure that other distributions also fit appropriately
  2. generalize the code to handle multiple covariates.
  3. generate variance estimates for the fitted parameters
  4. Calculate AIC for model selection
  5. Ensure that the function inputs and outputs play the same way as the current CP function(s) so that it can be a drop-in fix when it's done

I do not anticipate finishing this in the next three weeks but given that it is intended to be a drop-in module, I hope it does not create a bottleneck for the rest of the code

**Comment by prabie** [comment]
Question:  is it important to retain the survival package's parameterizations for the CP modeling?  I'd like to drop them and use base R functions.  For consistency in reports we'd still need to estimate modes (lognormal, loglogistic) or means (weibull, exponential) of fitted distributions, but that is a lot easier than trying to twist all of the parameterizations around to look like those that come out of survreg.

**Comment by ddalthorp** [comment]
Parameterizations of these distributions are a mess and difficult to follow. 

The survival package parameterizations are the most natural for fitting survival models and simulation, and there are some semi-knotty statistical issues that come up when estimating with interval-censored data. survival package addresses (most of) those neatly and reliably, and I'd be very cautious in trying to replace its fitting/functionality. 

That being said, for reporting purposes it makes great sense to translate the survival parameters to more familiar forms. The software currently uses the ppersist function from EoA for integrating CP into g and requires the EoA parameterizations of the distributions, which largely follow base R:

1. exponential: b = 1/rate ; exp(coef) in survival

2. Weibull: 
a = shape, b = scale in base R
a = 1/scale, b = exp(coef) in survival

3. lognormal:
 a = sdlog^2, b = meanlog in base R
a = scale^2, b = coef in survival

4. log-logistic: 
a = shape, b = scale in actuar package (base R does not have log-logistic)
a= 1/scale, b = exp(coef) in survival
NOTE: The actuar parameterization of log-logistic is the same as Wikipedia's EXCEPT the names are reversed.

**Comment by ddalthorp** [comment]
PR: "I have this solved for the single covariate case & have tested it for Weibull-distributed data."

Details? e.g., how fit, what kind of data (censoring in your intervals), what kind of test...

**Comment by ddalthorp** [comment]
PR: "3. generate variance estimates for the fitted parameters"

Need full variance-covariance matrix on a scale where estimated parameters are asymptotically MVN.

**Comment by prabie** [comment]
@ddalthorp 
You'll have to hold tight until I have time to clean up the code for full details but the short version is that I am fitting base-R parameterized weibull, and lognormal distributions, and FAdist-parameterized log-logisitic distributions.  I'm using nlminb() to fit, and generating interval-censored data.  For a single test case in each distribution I'm getting identical parameter point estimates (to 7 decimal places) to those generated by survreg (I fit the covariate levels separately in survreg).  I haven't tried exponential yet because my code assumes two parameters.

I think we should dump the hot mess that are the parameterizations in the survival package, but continue to report medians for llog and lnorm, and means for the other two.

**Comment by ddalthorp** [comment]
What are you using for your likelihood function?

How are you scaling your parameters?

And why not use optim instead of nlminb? (I believe the later doesn't return the hessian.)

**Comment by studyvin** [comment]
Food for thought. John Nash (https://www.jstatsoft.org/article/view/v060i02/v60i02.pdf) indicates that optim should not be used any more.

**Comment by ddalthorp** [comment]
I (mostly) agree with Mr. Nash. Currently there are several different optimization functions that all do something a little bit different...optim, contrOptim, optimize, uniroot, nlminb, etc. Putting them all into one umbrella package (optimx) makes good sense. Easier to maintain. Easier to keep track of parameter choices for a single function than keeping track of a bunch of different function names, each with its own parameter names, formats, and definitions and its own structure for return values. 

I suggested optim rather than nlminb because if you are fitting an MLE and have your parameters on the right scale, your betahat vector should be pretty close to multivariate normal with varhat(betahat) = inverse(hessian), which optim will return for you if you ask it to. optimx too can return the (estimated) hessian. nlminb will not.

**Comment by prabie** [comment]
hessian() in the numDeriv package will get the job done, i think.

On Nov 9, 2017, at 5:48 PM, ddalthorp <notifications@github.com> wrote:

I (mostly) agree with Mr. Nash. Currently there are several different
optimization functions that all do something a little bit
different...optim, contrOptim, optimize, uniroot, nlminb, etc. Putting them
all into one umbrella package (optimx) makes good sense. Easier to
maintain. Easier to keep track of parameter choices for a single function
than keeping track of a bunch of different function names, each with its
own parameter names, formats, and definitions and its own structure for
return values.

I suggested optim rather than nlminb because if you are fitting an MLE and
have your parameters on the right scale, your betahat vector should be
pretty close to multivariate normal with varhat(betahat) =
inverse(hessian), which optim will return for you if you ask it to. optimx
too can return the (estimated) hessian. nlminb will not.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/ddalthorp/GenEst/issues/27#issuecomment-343340496>, or mute
the thread

**Comment by ddalthorp** [comment]
PR: "hessian() in the numDeriv package will get the job done, i think."

No doubt!

**Comment by ddalthorp** [comment]
Chesterton's fence and CP parameterizations...

Let's not jettison the 'survival' parameterization unless we have a more compelling reason than that they look different from the R base package parameterizations. We can use the 'survival' parameterizations for modeling and then translate to R parameterizations for reporting.

There are reasons why 'survival' package (and SAS) use the location/scale parameterization rather than a shape/scale parameterization like the R base package uses. I don't know what all the reasons are, but one of them appears to be that the distribution of the betas under the 'survival' parameterization appear to approach MVN faster than those for the R parameterizations. [There's an inherent skewness with the R parameterizations because of the left wall at zero for most of the parameters.]

E.g.:
### a test: distribution of the betas under 'survival' parameterization vs. R
# Weibull persistence, 15 carcasses in persistence trials
nsim <- 1000
res<-list(surv = array(dim = c(nsim, 2)), R = array(dim = c(nsim, 2)))
for (simi in 1:nsim){
  x <- rweibull(15, .6, 6) # mean = 9 days
  survx <- survival::Surv(time = x, event = x^0)
  res[['surv']][simi, ] <-  survival::survreg(survx ~ 1, dist = 'weibull')$icoef
  res[['R']][simi, ] <- optim(c(2,50), function(dfab) -sum(log(dweibull(x, dfab[1], dfab[2]))))$par
}

# plots of fits to normal distribution of estimators for Weibull parameters under:
#1. 'survival' parameterizations, and
#2. 'R' parameterizations
# The following figs should plot to straight lines:
par(mfrow = c(2,2))
qqnorm(res[['surv']][,1])
qqline(res[['surv']][,1], col = 2)
mtext(side = 3, line = 0, "survival parameterization, coef", cex = 0.8)
qqnorm(res[['R']][,1])
qqline(res[['R']][,1], col = 2)
mtext(side = 3, line = 0, "R parameterization, shape", cex = 0.8)
qqnorm(res[['surv']][,2])
qqline(res[['surv']][,2], col = 2)
mtext(side = 3, line = 0, "survival parameterization, log(scale)", cex = 0.8)
qqnorm(res[['R']][,2])
qqline(res[['R']][,2], col = 2)
mtext(side = 3, line = 0, "R parameterization, scale", cex = 0.8)

**Comment by prabie** [comment]
You had me at the argument about base-R parameterizations hitting a wall at zero.  I agree we should retain the survival package parameterizations.

**Comment by DAPPERstats** [comment]
this is marked as a version 1 release. are we still planning to include this? if so, do we have an eta on the functions?

**Comment by prabie** [comment]
Juniper,

I will have something ready end of next week.


* Paul Rabie,  Ph.D*
*Research Biometrician*
*ESA certified Ecologist*

Western Ecosystems Technology, Inc.
Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
307-755-9447
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by DAPPERstats** [comment]
great! thanks for letting me know.

**Comment by DAPPERstats** [comment]
in digging into the code, I think it makes good sense for us to shift to using `optim` for CP unless there are any numeric instability issues (I haven't hit any yet, but please tell me if any of you hit them). the main reasons being simplicity of code compared to using `nlminb` (`optim` automatically runs the hessian and `nlminb` can't be coerced to do it, thus requiring more code, the more intuitive reading of arguments and clearer scope of `optim` and the fact that we're already using `optim` elsewhere and it's nice to keep it our routines using the same underlying machinery if possible.

I recognize that there are LOTS of numerical optimization routines and many of them have quirks and such, but if optim works for the cases we're dealing with here, there's no need to use something more newfangled, and we can always lock-in the historic version of the R code if we need to (if stuff deprecates).

**Comment by DAPPERstats** [comment]
re: different parameterizations, @prabie is the code in your functions using the correct parameterization for what we want now? If not, what should I change? (don't worry about updating your functions in your branch, just let me know the edits I need to make)

**Comment by prabie** [comment]
Juniper ,

I don't have a super strong opinion about the optimizer we use.  I used to
default to optim for the same reasons you describe, but I and others at
WEST have found that when other optimizers fail,  nlminb often succeeds.
There's also a fair amount of noise on the blogs and boards about optim
returning a poor approximation to the Hessian.  I haven't delved into that
discussion to try to understand it, and quick searches have not produced
anything that looks like a definitive demonstration.  But not hearing noise
about nlminb, and finding that it tends to succeed when optim fails, nlminb
has become my default.

Others might have more data-driven opinions.

Meanwhile, here's one example of somebody who felt mis-used by the Hessian
returned by optim()
https://diffuseprior.wordpress.com/2012/05/28/optim-youre-doing-it-wrong/


* Paul Rabie,  Ph.D*
*Research Biometrician*
*ESA certified Ecologist*

Western Ecosystems Technology, Inc.
Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
307-755-9447
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by prabie** [comment]
Juniper,

We're using the same parameterizations as the survival package.  As far as
I know, those are the parameterizations we want.


* Paul Rabie,  Ph.D*
*Research Biometrician*
*ESA certified Ecologist*

Western Ecosystems Technology, Inc.
Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
307-755-9447
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by ddalthorp** [comment]
"We're using the same parameterizations as the survival package.  As far as
I know, those are the parameterizations we want."

Agreed. The 'survival' parameterizations were chosen specifically to have nice asymptotics, which we're using.

**Comment by DAPPERstats** [comment]
thanks for the background on your thinking on/choice of optimizers
the link you shared is definitely illuminating, although the set up of that model has some serious issues, as raised in the comments, regarding co-linearity and scales of predictors

**Comment by ddalthorp** [comment]
PR: "I don't have a super strong opinion about the optimizer we use."

It may not make much of a difference in this case, but fwiw the guys who are in charge of the nlminb function in R recommend using optim instead (see, e.g., the "see also" in ?nlminb ). nlminb is still included in R apparently solely for legacy code compatibility (see intro to the function in ?nlminb). 

As for going from:
(A) someone finding a data set where the default settings for optim didn't do as well at Hessian calculation as a different approach to optimizing a specific type of problem and recommending the maxLik function as an alternative,

to:
(B) using nlminb + hessian in place of optim, 
take a look at JC Nash's note in the comments thread. 

Unless there's a compelling reason to use an obsolete function that its maintainers recommend not using (preferring optim instead), let's go with optim for now. 

In future, we may run into fitting issues that require more thorough reflection because optimization with many variables is often a dicey game. I'm not sure how 'survival' does the fitting, but it might be good to know if it uses a simple optim or a different approach tailored to specifically to address issues arising with survival models.

**Comment by DAPPERstats** [comment]
addressed with #77
