### ISSUE TITLE
how do I stop GenEst?

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#363]
runGenEst()

Listening on http://127.0.0.1:4000
# I hit escape
> 
# Downloaded ;latest GenEst and tried to install it...
> install.packages("V:/Research Projects/955 Generalized Estimator/Software Development/GenEst.zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/mhuso/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘GenEst’ is in use and will not be installed
> 
# I killed Genest in my browser and in my RStudio window. What else do I need to do?

**Comment by ddalthorp** [comment]
There may be a simpler way, but I think you need to restart R...that's what I do anyway when I want to install a new version of a package that is "in use".

**Comment by mintzj** [comment]
Interesting, I hadn't run into that before.  I don't think it is because you stopped it incorrectly, it's just there is a DLL file that's still running after the app closes (even if you detach the library).  I tried a few different ways to shut down the app but I couldn't find one which avoids the DLL still being in use.

**Comment by ddalthorp** [comment]
It's not a DLL issue. It's that someone important (Windows or R) thinks the package folder is in use when you have loaded into your R session (regardless of whether you have detached it) and will not allow the new installation to delete it until it hears from someone more important (you) to do otherwise. I don't know how to tell it that except by closing and restarting R.
