### ISSUE TITLE
the semi-regular issue with calcSplits persists

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#369]
@ddalthorp I am running into the "need finite 'ylim' values" error resulting from `calcSplits` occasionally returning missing-values (now `NaN`s) instead of actual values.

i ran into it in the vignette building

![image](https://user-images.githubusercontent.com/23511502/41502732-f06d739e-7175-11e8-8828-ead968f80480.png)

and then went into `command-line-example.Rmd` to see if i could recreate it

it's clearly a stochastic situation at some level. here are repeat splittings of the same `eM` object by the same set of splits, which only sometimes gives the `NaN` result. 

![image](https://user-images.githubusercontent.com/23511502/41502779-e872f00a-7176-11e8-942a-6902a643317b.png)

i split again after this and had fine values be returned, so it's not a persistency issue of some kind

**Comment by ddalthorp** [comment]
Are you using  cbinom v1.1?

**Comment by ddalthorp** [comment]
And the new version calcSplits with the Ft array (in src)?

**Comment by DAPPERstats** [comment]
yes and yes

i did a clean install of all of the packages and have been working with the most up-to-date everything from the master branch, which installs cbinom v1.1 (verified that) and `tsplit.cpp` includes `Ft`

**Comment by ddalthorp** [comment]
Last week, I looped through the vignettes about 120 times with no problem. Just now, I got a crash on the 14th time through. This seems to be an issue with how Rcpp deals with R data structures. I thought I had a cure, but apparently not. Maybe just something that alleviated the symptoms a bit. I'll look into it again.

**Comment by ddalthorp** [comment]
Sheesh. In looking for an errored data set to work with, I've looped through all three vignettes 50 times with no problem. Each run-through takes about 1 minute. Will it crash soon?

**Comment by DAPPERstats** [comment]
this happened both times i tried

**Comment by ddalthorp** [comment]
I see a possible problem...` plot.pkmSet` asks for user input, and the wind vignette has a few calls to that. I commented out those calls in my testing code, but if you try to steamroll through them by force in a vignette build, I'm not sure how that would turn out.

[I do see that the loop through the pkSet figs should NOT loop through with user input if the specific model is of length one. My bad. Sorry! ...should be an easy fix]

**Comment by DAPPERstats** [comment]
ok then there are files that you are working with (and building from) locally that aren't on github, otherwise installation of it from github with a vignette build would work.

**Comment by ddalthorp** [comment]
yup. over 100 reps now. No problems. I'll take a look later to see where there might be a mismatch.

**Comment by ddalthorp** [comment]
GitHub is a mystery to me. The seeking-beta branch says: "31 commits ahead and 9 commits behind master branch." I thought I merged seeking-beta into master last night, and GitHub told me something like "successfully merged." The travis check worked on seeking-beta. It worked on master branch too. 

I do not understand what the "31 commits" are all about.

[My loop is up to 150 now.]

**Comment by ddalthorp** [comment]
In seeking-beta branch, I see a note that says "This branch is 34 commits ahead, 10 commits behind master." I don't know what that means. Or I don't know what "merge" means because I just merged seeking-beta into the master branch. I was imagining that this would push new work done in the beta branch into the master branch so beta would no longer be 34 commits ahead. But GitHub tells me it still is. Or maybe GitHub isn't telling the truth?

**Comment by ddalthorp** [comment]
I just cloned the master branch to my desktop, ran devtools::build() from RGui [which builds vignettes unless vignettes = FALSE is explicitly set], and then, from the "Packages" menu in R, I clicked "Install package(s) from local files..." to compile and install. 

No problem. 

[...and my loop is up to 230 now]

Maybe there's an issue with the translation from GitHub to R on your desktop?

**Comment by DAPPERstats** [comment]
no, it's definitely an issue with what's up on the github repo. i've confirmed that on multiple machines, from a completely clean R environment (ala a naive user to GenEst), I am getting the error.

I remove all instance of R, delete the local libraries, and restart the machine.
I install R 3.5.0
I install devtools from the R command line:
```
install.packages("devtools")
```
I install GenEst from the master branch on GitHub
```
devtools::install_github("ddalthorp/GenEst")
```
or using the most recent windows binary you loaded. I have confirmed this for both methods on multiple machines. If I use the zipped build, I download the dependencies using
```
install.packages("devtools")
devtools::install_deps(paste0(.libPaths()[1], "/GenEst"))
```
both cases get me a functioning version of the GenEst package (i.e. the builds don't break or thrown any warnings).

I then run the following block of code:
```
library(GenEst)
data(mock)
data_SE <- mock$SE
data_CP <- mock$CP
data_SS <- mock$SS
data_DWP <- mock$DWP
data_CO <- mock$CO

pkmModSetSize <- pkmSetSize(formula_p = p ~ Visibility*HabitatType,
                   formula_k = k ~ HabitatType, data = data_SE,
                   obsCol = c("Search1", "Search2", "Search3", "Search4"),
                   sizeclassCol = "Size"
                 )

cpmModSetSize <- cpmSetSize(formula_l = l ~ Visibility*Season,
                   formula_s = s ~ Visibility, data = data_CP,
                   left = "LastPresentDecimalDays",
                   right = "FirstAbsentDecimalDays",
                   dist = c("exponential", "lognormal"),
                   sizeclassCol = "Size"
                 )

pkMods <- c("S" = "p ~ 1; k ~ 1", "L" = "p ~ 1; k ~ 1",
            "M" = "p ~ 1; k ~ 1", "XL" = "p ~ 1; k ~ HabitatType"
          )
cpMods <- c("S" = "dist: exponential; l ~ Season; NULL",
            "L" = "dist: exponential; l ~ 1; NULL",
            "M" = "dist: exponential; l ~ 1; NULL",
            "XL" = "dist: exponential; l ~ 1; NULL"
          )
pkmModSize <- trimSetSize(pkmModSetSize, pkMods)
cpmModSize <- trimSetSize(cpmModSetSize, cpMods)

eM <- estM(data_CO = data_CO, data_SS = data_SS, data_DWP = data_DWP,
        frac = 1, model_SE = pkmModSize, model_CP = cpmModSize,
        seed_SE = NULL, seed_CP = NULL, seed_g = NULL, seed_M = NULL,
        kFill = NULL, unitCol = "Unit", dateFoundCol = "DateFound",
        datesSearchedCol = "DateSearched", sizeclassCol = "Size", nsim = 1000)
#
M_SbyC <- calcSplits(M = eM$Mhat, Aj = eM$Aj, split_SS = "Construction",
            split_CO = "Split", data_SS = data_SS, data_CO = data_CO
          )
summary(M_SbyC)
plot(M_SbyC)
```

Everything up to the comment line runs smoothly and I can plot `eM` just fine. The split of `eM` that happens after the comment line runs, and generally speaking will return a fine answer. However, once every five or so times I repeat that set of lines (just what's after the comment character, not the whole thing), I get a return of `NaN` values like I showed in the OP image.

**Comment by ddalthorp** [comment]
OK! 

My loop finally crashed, but I believe it must have been because of unusual simulation draws for cp parameters because it threw a warning in ppersist a few lines after rcp and then errored on
```
 cpi <- findInterval(aj, c(0, min(xuint) + cumsum(cells[[xi]]$CPrep)),
        rightmost.closed = T)
```
which sounds like an anomalous value in xuint, which is derived from cpsim values. I didn't save any values within functions, but I guess it is not a surprise to get an anomalous simulated values when we're generating billions of RV's. 

This is a different issue, but I'll look into it.

**Comment by ddalthorp** [comment]
Hmm...This is different from what's happening for me. I cloned the master branch to my desktop, built using devtools::build() from the command line, installed from the Packages menu. Then, I ran everything but the last three lines of your code and put the last three lines in a loop.  Three thousand reps without a hitch. 

Running the whole vignette snippet (minus the data input lines)...much slower than just doing the splits, but I'm up to 40 reps without a hitch. 

Maybe my machine "knows" something outside of what I just downloaded from GitHub?

I'll delete the old package version explicitly and try again on a new R 3.5.0 session (and a 3.4.2 session for good measure).

**Comment by ddalthorp** [comment]
The loop is running, using the build I put together using strictly the files I downloaded from GitHub a couple hours ago (via the "Download zip") button. No problem on the build. No problem on the compile or install. Loop is up to 90 now with no sign of problem. 

Before the build, I deleted my old GenEst package from "library". Just to be sure, I tried `library(GenEst)` and heard `Error in library(GenEst) : there is no package called ‘GenEst’`". Then I did the build and loaded the freshly-minted package and started looping through the vignette snippet

**Comment by ddalthorp** [comment]
up to 275, and I'm going to bed

**Comment by DAPPERstats** [comment]
you're not doing exactly the same thing i did... i downloaded the package as a user would (following the instructions on the main repo page).

in any case, when i do what you said here, i get the error on the package build
![image](https://user-images.githubusercontent.com/23511502/41505611-5c517cb8-71c1-11e8-81ff-312725da6038.png) on multiple machines

**Comment by ddalthorp** [comment]
No, I'm not doing the same thing you are. I was checking the files that are on GitHub to see whether the package they build is right. The files appear to be right and seem to work fine if you install using the procedure I used.  I tried it also on my home computer that has seen nothing of GenEst before and needed almost all the packages to be installed, which I did via install.packages(c('binom', ... ). No problem in building, compiling, installing, or running.

I don't know what `devtools::install_github("ddalthorp/GenEst")` is supposed to do, but apparently it does not build the package from the DESCRIPTION, NAMESPACE, R, src, etc. files that are in the repo. That's what I'm doing. And it works. 

Also, I did not update the GenEst.zip folder because the figs and menus in the latest version are not integrated into the latest error-checking. and traffic directing. I will upload a new zip and tar.gz and zip with GenEst name shortly. 

On my home computer, after cloning the master branch:
![image](https://user-images.githubusercontent.com/30092223/41507822-2f3bcbb0-71ef-11e8-9ab5-4b45c6da2143.png)
and after installing devtools and installing everything else that was needed via:
![image](https://user-images.githubusercontent.com/30092223/41507832-6161360c-71ef-11e8-8d92-03474fdf4ef8.png)

 

I built the package without issue:
![image](https://user-images.githubusercontent.com/30092223/41507836-74af3434-71ef-11e8-9386-e5f83a488ecf.png)


 ...compiled and installed:
![image](https://user-images.githubusercontent.com/30092223/41507843-90335bb8-71ef-11e8-88de-626dc60c8e33.png)

And ran your vig snippet...100 times. No problem with any of it.

**Comment by ddalthorp** [comment]
My home computer is running R 3.4.3

**Comment by ddalthorp** [comment]
I did not upload a GenEst.zip folder because I'm not clear on what format is required for your link. I did upload a GenEst_0.0.10.8.zip and GenEst_0.0.10.8.tar.gz to auxiliary.

**Comment by ddalthorp** [comment]
I tried `devtools::install_github("ddalthorp/GenEst")` on my home computer. First try I had problems with `digest` package. But then I installed that from CRAN and then no trouble on build, install, compile, run, loop.

**Comment by DAPPERstats** [comment]
i'm trying to run completely clean installs on multiple machines right now, but it looks like the builds you recently added to the auxiliary folder were made with an old version of R again

![image](https://user-images.githubusercontent.com/23511502/41510971-db020cce-7222-11e8-8551-548fa850314e.png)

**Comment by DAPPERstats** [comment]
`install_github` is just a set of wrapper functions on `install.packages` that points everything to do a full installation from guithub, rather than CRAN

**Comment by DAPPERstats** [comment]
i have run into the same issue installing the package on multiple machines, including one that hasn't even booted up in over a year before today, again today.
![image](https://user-images.githubusercontent.com/23511502/41511154-47e1d77c-7226-11e8-8549-b4f3614e2119.png)

**Comment by DAPPERstats** [comment]
sessionInfo for it on my standard use machine (with a completely clean reinstall of everything R associated including R, Rtools, and all package files)

![image](https://user-images.githubusercontent.com/23511502/41511165-71eb1e8e-7226-11e8-8c8b-318b5563fcfc.png)

**Comment by DAPPERstats** [comment]
and here's the sessionInfo from the dusty old machine I tried it on, too

![image](https://user-images.githubusercontent.com/23511502/41511197-e573fe5c-7226-11e8-9442-7d757e0fa888.png)

**Comment by DAPPERstats** [comment]
can you share the output from `SessionInfo()` on the machines where everything has worked for you?

**Comment by ddalthorp** [comment]
My home computer:

![image](https://user-images.githubusercontent.com/30092223/41513281-4426a572-724e-11e8-8044-e3b7a1186211.png)

**Comment by ddalthorp** [comment]
My work computer:

![image](https://user-images.githubusercontent.com/30092223/41513306-9836c688-724e-11e8-8b8c-1facc7c18b45.png)

**Comment by ddalthorp** [comment]
I built the 0.0.10.8 from R 3.5.0 but the .zip I put up was compiled from R 3.4.3 (I may not be able to get the paths and permissions right w/o IT b/c of permissions issues).

**Comment by DAPPERstats** [comment]
thanks!
i'm baffled at this point, to be honest.
my best guess is that it's something about some dll or something, but i honestly don't know how that could still be the case.

in any case, this maybe-error-maybe-not tracking once again has me thinking seriously about refactoring the code base so it's much **MUCH** easier to track changes.
it will also make it much ***MUCH*** easier to build tests that will allow us to verify that all of our functions are producing the right output, even when we change other (seemingly unrelated) code. it's also aligned with the work i'm doing right now with the figure code and the gui code updates

**Comment by ddalthorp** [comment]
I don't think it's a problem in the code but, rather, in the GitHub/build/compile web. It may be related to a compiler compatibility issue because the problem seems to be in the communication between C++ and R. The same data going into C++ (calcTsplits) sometimes comes back with the right answers and sometimes NaN's. I believe Dirk Eddelbuetel and Hadley Wickham have different ideas about how to set 
up the build and compile tools. Maybe that has something to do with the current puzzle. 

I had no problem setting up the package, running the vig snippet, and looping it on my work and home computers and Lisa's home computer. I installed all dependencies from CRAN binaries without using Git wrappers. It runs and runs and runs with no problem on any of it.

In any case, it seems clear that is a build/compile issue rather than a code issue.

I think the focus should be on whittling down the issues list and getting product out (with a simple .zip and a .tar.gz in the file list) instead of spending a bunch of time reorganizing.

**Comment by ddalthorp** [comment]
When I do the builds as I've done, instead of NA's coming out occasionally, I'm getting (essentially) -Inf every once in awhile, so the graphs are "drawable" but they are non-sensical...will look into it a little more today.

**Comment by ddalthorp** [comment]
I thought of a simpler way to do the tsplits and will code it up forthwith.

**Comment by ddalthorp** [comment]
The simpler way was WAY slower. 

Took a closer look at the original C++ code and found a simple error...forgetting to initialize one array value to zero. Sometimes it would get initialized to zero anyway by chance, and sometimes it would get initialized to garbage. That's fixed now and should be good to go.

**Comment by mintzj** [comment]
Great news!  This was a deviously tricky bug.
