### ISSUE TITLE
CP Estimates

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#386]
Few people will know how to interpret estimates of Location and Scale, although they will be useful for input into other estimators. Can we add estimates of r and CI for an arbitrary search interval? I suggest using the mode (the interval most commonly occurring in the Search Schedule data) because I think it will provide a more relevant measure to the user than a mean, say, which may not exist as an interval at all. But Dan likes the mean :-) I'm open to either... I'd just like to see some measure of r-hat presented somewhere in GenEst.

**Comment by DAPPERstats** [comment]
the short answer is that yes, we can certainly add any of these kinds of estimates to the GUI
the longer answer is a series of questions:
- how important is this (pre-beta or post-beta)?
- what is r?
- can someone else (@ddalthorp ?) code up the calculation of that estimate if it doesn't already exist?
- what would the estimate look like (text? downloadable table? figure?)
- for an "arbitrary search interval" do you mean "an interval that we pre-define" or "an interval that the user could toggle"?

**Comment by ddalthorp** [comment]
r is the probability that a carcass persists until the first search after arrival. 

The calculation is ppersist(..., t_arrive0 = 0, t_arrive1 = I, t_search = I), where I is the selected interval. 

OR:
```
rsim <- ppersist(pda, pdb, dist, 0, I, I)
r_CI <- quantile(rsim, prob = c(alpha/2, 1-alpha/2))
r_mean <- mean(rsim)
```
where pda and pdb are the simulated cp parameters.

For choice of I, mode is not the greatest because it can so easily be a largely non-descriptive descriptive statistic. But it doesn't matter very much. The r statistic is not doing anything, it just gives the user a rough idea of what the persistence probabilities are. Maybe use the mode (or even a generic 7) and give the user an option to override.

**Comment by juniperlsimonis** [comment]
handled in v 0.2.19  #573
