### ISSUE TITLE
Installation help?

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#400]
I just downloaded the latest and used the steps I always do to install and run GenEst. I got the following error:
utils:::menuInstallLocal()
package ‘GenEst’ successfully unpacked and MD5 sums checked
> require(GenEst)
Loading required package: GenEst
Failed with error:  ‘package ‘GenEst’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version’
In addition: Warning message:
package ‘GenEst’ was built under R version 3.5.0 

I first opened R i386 3.4.4.4 and got this message. So I exited and opened Rx64 3.4.4 and got the same error. So, apparently I have to update my R to 3.5.0?

**Comment by mhuso** [comment]
Just updated to R3.5.0. Had to require(GenEst) 9 times to find out one at a time that these dependencies weren't installed. Can we add them as dependencies in the initial installation? Or should we just give the user this command to run?
install.packages("DT","cbinom","gsl","gtools","lubridate","matrixStats","mvtnorm",
"shinydashboard","sticky")

**Comment by mintzj** [comment]
I think we could do that, so long as we wrap the names of a the packages in a c(). 
```
install.packages(pkgs = c("DT","cbinom","gsl","gtools","lubridate","matrixStats","mvtnorm",
"shinydashboard","sticky"))
```

**Comment by ddalthorp** [comment]
or even: 
`install.packages(c("cbinom", "devtools", "digest",  "DT", "gsl", "gtools", "htmltools", "lubridate",   "matrixStats", "mvtnorm", "Rcpp", "shiny", "shinydashboard", "sticky", "survival", "testthat"))`

or maybe (as suggested in the install instructions on our GitHub front page):
```
install.packages("devtools")
devtools::install_deps(paste0(.libPaths()[1], "/GenEst"))
```
This is something that beta testers will probably be doing....and something that we USUALLY ignore safely because we all have the required packages (until we do the upgrade to R 3.5.x and not do all the library updating in one sitting).

**Comment by mhuso** [comment]
Oh... right. I should have approached it from the instructions. It looks like we have it already covered.
