### ISSUE TITLE
check the "look" of the vignettes

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#403]

**Comment by mintzj** [comment]
Most of the plots looked fine except one which got in by accident I think.
In the command line example, it looks like plot `plot(gsGeneric)` is supposed to be omitted.  

The only other plot which stood out as unattractive was  `plot(M_speciesseason)` in the wind examples, however we follow it with a description of how to make it better using `plot(transposeSplits(M_speciesseason))`, so I think that's probably ok to leave in.

I will try to fix this but I have been having some trouble with my R-tools since upgrading to 3.5.

**Comment by DAPPERstats** [comment]
for the command line example one, the "(not shown)" text should be removed from the vignette, rather than the plot being omitted

let me know if you'd like me to do this, jeff, or if you've got the vignettes covered

**Comment by mintzj** [comment]
I switched back to 3.4 and things are working now.  I'll leave the plot in if you want.

**Comment by mintzj** [comment]
I think I will just make it centered, long and narrow.  It doesn't look too bad if we do that, though it uses a bit of vertical space.
