### ISSUE TITLE
GUI: note in "Model Selection" tabs

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#490]
At least two reviewers have remarked that the model selection process is confusing. It seems that they did not understand that the default selection is the best AICc model and that clicking on tab with no other action selects those models. Would it make more sense to list the models by AICc but have no default selection, thus requiring users to make an explicit choice?

**Comment by juniperlsimonis** [comment]
this is handled more cleanly now in v 0.2.7 #543 
it looks like you had put a patch on this, but it was buggy and didn't fully resolve the issue.
now the selectizeInput that creates that selection drop down sets it up properly but doesn't have a default selection (rather than selecting an empty character value), which properly limits the downstream code. big benefit of the new patch is that it also means that the selection of a model (or models) is reset when the model is re-run, so the confusing situation (where you only *need*ed to click over to the model selection tab the first time) is eliminated, and now the user will explicitly need to select the model(s) each time the set is re-fit
