### ISSUE TITLE
Model names

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#5]
We need to come up with a clean notation/presentation style for the models

drop "~" notation (esoteric to R)
replace "1" with "intercept"
format fixed k better (currently "fixed_at_")

need to consider width of dropdown menus as well (can we change this?)

**Comment by mhuso** [comment]
for p and k, I suggest only listing the covariate models in two columns, one headed p, the other k. As long as we have enough width in our drop down menu, this should work. 
Eventually we will add another model for k, i.e., k=1, giving us a total of 30 models. Listing Intercept for the constant k model and 1 for the k = 1 model should be clear, right?

**Comment by DAPPERstats** [comment]
@mhuso what do you think about having the model selection dropdown menus (on  the "figures" and "model selection" subtabs) having separate selections for each input (p and k or covariate and distribution)? this would result in two selections happening for each input, rather than one, but it will simplify the presentation of the dropdown options and make it much easier to toggle between the options. however, it does have the downside of us not being able to sort across all of the model options together (so that the dropdowns are sorted by AICc), although i think we can have the default selection in each dropdown be (in combination) the best AICc model, so the model that gets auto-populated will be the best model, but if you want to choose the second best model, you'd have to go back to the AICc table tab.

**Comment by mhuso** [comment]
Since the p and k are correlated and fit together, it seems like we should keep them together in the model selection and figures dropdowns. I was just trying to get at a little tidier way of presenting the models. If we have (the equivalent of) three columns, the first listing p models left-justified, the second listing k models left-justified, and the thirds listing delta-AICc right-justified, the models would be easier to read. But p and k selections wouldn't be separate... everything on the same row would still be single model that could be selected. Maybe I'm not understanding the limitations of the program. Is the pull-down limited by character width? or if we change the format is it difficult to link back to the fitted models?

**Comment by DAPPERstats** [comment]
model names are updated to be more intuitive in the GUI, will be included in the next pushed update.
