### ISSUE TITLE
what is kFill?

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#563]

**Comment by juniperlsimonis** [comment]
it's the value that's used to fill in the k when it wasn't fit or fixed (because there was only one observation and no k fixed)

what is the issue?

**Comment by ddalthorp** [comment]
just trying to understand the pathways...

kFill applies to the situation where there is only one search occasion for each trial carcass and k is not fixed by the user during the fitting of the SE model but then wants to estimate M or g? How is this different from kFixed in pkm?

**Comment by juniperlsimonis** [comment]
when kfixed isn't input either, you get a model with `k not estimated`, so you need to fill in k

**Comment by ddalthorp** [comment]
you need to fill in k only if you want to estimate M or g. 

If they fill in k under the estimate M or estimate g tab, that k is used in estM or estg but does not get inserted/stored into the pk model?

**Comment by juniperlsimonis** [comment]
correct, and only in that one specific instance where you didn't already fix k in the model earlier and you only have one search...it's a pretty edge case

and yes, the filling of k is downstream, hence the different name... although it's in the GUI facing the user as "assume k" rather than "fill k", but it's in the code as fill everywhere

**Comment by ddalthorp** [comment]
requiring kFill to be dealt with in "Searcher Efficiency" model rather than in estM and estg

(patched on GUI side in "dan" branch...command-line patch pending)
