### ISSUE TITLE
rpk output

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#71]
Change output of rpk so that p and k are in parallel columns and different classes separate levels rather p and k in separate levels with classes in parallel columns.

**Comment by DAPPERstats** [comment]
ooh, good idea!
just to make sure i follow, by "levels", do you mean elements of the list? 

so, say for 10000 reps of 10 cells of p and k
rather than a length-2 list with each element being a 10000 x 10 matrix, you want a length-10 list with each element being a 10000 x 2?

and then for names, is it ok for each element name to be the cell name and the column names of the matrix to just be "p" and "k"?

**Comment by ddalthorp** [comment]
exactly, because we do so much classwise estimation so it's nice to keep the p and k columns parallel and the classes separate (and no row names).

**Comment by DAPPERstats** [comment]
totally.

to ensure flexibility, i'd propose we have the output still be a list (of length 1) when the model is just the intercept-only model. (that is, not have it condense to just a matrix, but rather be a length-1 list with the one element being the matrix)

wait, no row names, as in you want me to remove the row names? they're in there now as the iteration of the random pull, and since the cellwise values aren't independent of each other, we need to make sure we retain the rows of the different elements are still linked, right?

**Comment by ddalthorp** [comment]
The intercept-only model is a puzzle. My original 3-d array format was a bit awkward when there were no covariates, but a list format may be easier for a command-line user to untangle.

row names...yes, there is correlation structure that needs to be preserved, but that comes automatically in the way the data are generated. It would take work to break that. Do you ever refer to row names in  these structures in any of your code? Are they used?

**Comment by DAPPERstats** [comment]
i don't use the row names as of now, but I also haven't gotten to the spot where it would be used yet. in particular, I've thought about using it to verify that the simulated data are still aligned properly. 
it would take some effort to break the structure, but not that much. I could definitely see it happening if someone were to sort one of the elements for some reason and overwrite it. 
is there a down side to having the row names? it's a single line of code and it doesn't change the class or format, but lmk if there's some other negative effect of it.

**Comment by ddalthorp** [comment]
Yes, if someone was intent on screwing up the columns, they could do so. Carrying along row names and double-checking whether someone scrambled the orders would make it slightly more difficult for them to do so. But if they overwrite the a column for any reason, it completely messes up the data, whether they maintain the same order or not. 

It's ugly in output, slower in execution (especially if you are going to routinely double-check ordering before using the data), and uses more memory. The value of such a check seems miniscule to me. Maybe at some point, we'll find that people do like to scramble the orders of some of the columns but otherwise leave the values fixed (actually, I can almost imagine just a scenario...but sometimes I have an overly active imagination), and at that point we might want to implement a check against that. 

In the meantime, how about no row names?

**Comment by DAPPERstats** [comment]
changed in v0.0.3.0
