### ISSUE TITLE
use parametric bootstrap for cellwise tables

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#76]
in both pkm and cpm

**Comment by ddalthorp** [comment]
I looked back at my original code and am having second thoughts on changing it. It looks right to me. The assumption of the parametric bootstrap is mvnorm with the estimated mean and covariance. Using logit(qnorm...) should give you the same answer as doing the parametric bootstrap (but MUCH faster and without any need for recalculating or carrying around big data), no?

**Comment by ddalthorp** [comment]
(faster and more accurate)

**Comment by DAPPERstats** [comment]
i'm fine with that. 
what should we do about the cpm model then, since we don't get the scale values out? we have the MLE values, but not the medians or CI values.
this is what's in the "cellwise" table, which is printed out with the model at the command line and is included in the gui

**Comment by ddalthorp** [comment]
Doesn't Paul's model give a betahat column and varbeta for MLE? 

If so, then betahat ~ mvn(betahat, varbeta) and you should be able to extract summary statistics from there. In particular, marginal distn is betahat[i] ~ n(betahat[i], varbeta[i, i]), so logit(betahat[i]) for median and logit(qnorm(betahat[i], sd = sqrt(varbeta[i, i]))) for CIs.

**Comment by ddalthorp** [comment]
"logit" 
Heh-heh! My fingers got ahead of me there...you'd of course want to do whatever transformation you need to get the parameters on the scale we need to see (different for different survival models, but not logit!)

**Comment by DAPPERstats** [comment]
yes, we get betahats from Paul's model.
i'm having a bit of trouble following what you've written... can one of you write out the pseudo code (or actual code) for that, please?

**Comment by ddalthorp** [comment]
OK. I'm getting a handle on what's going on. The CIs that are in your cellTable_loc are for persistence times (qsurvreg) rather than for the parameter estimates. Whether to show some summary statistics for persistence times or for rhat[Ir] = probability of a carcass that arrives at a random time (uniform) in an interval of length Ir persists until the first search or for neither is something we'll need to discuss.

But we do need to show summary stats for the parameter estimates on a cp model scale (i.e., shape and scale instead of betahat's). A simple example for Weibull for 0.05 quantile:
nparms <- dim(cellMM)[2]
p <- 0.05
# for scale (pdb):
exp(qnorm(p,
  mean = cellMM %*% betahat[1 : nparms],
  sd = sqrt(diag(cellMM %*% varbeta[1 : nparms, 1:nparms]))
))
# for shape (pda):
1/qnorm(1-p,
  mean = cellMM %*% betahat[nparms + 1:nparms],
  sd = sqrt(diag(cellMM %*% varbeta[1 : nparms, 1:nparms]))
)

This [exp(qnorm...) and 1/qnorm(...)] gives the parameterization used in ppersist (and R base package for Weibull).

For the other distributions, to translate the parameterizations from 'survival' to ppersist, use:
# exponential:
pdb = exp(betahat) # no scale parameter to worry about

# loglogistic:
pda = 1/betahat[scale parms]
pdb = exp(betahat[other parms]

# lognormal:
pda = betahat[scale parms] ^2
pdb = betahat[other parms]

**Comment by ddalthorp** [comment]
Wow. One must take care in writing ":" in GitHub comments.

**Comment by ddalthorp** [comment]
Dang. GitHub also automatically changed other parts of my Rscripts. Any way to have it post what you write instead of what it thinks you wanted to write?

**Comment by ddalthorp** [comment]
```
nparms <- dim(cellMM)[2]
p <- 0.05
# for scale (pdb):
exp(qnorm(p,
  mean = cellMM %*% betahat[1 : nparms],
  sd = sqrt(diag(cellMM %*% varbeta[1 : nparms, 1:nparms]))
))
# for shape (pda):
1/qnorm(1-p,
  mean = cellMM %*% betahat[nparms + 1:nparms],
  sd = sqrt(diag(cellMM %*% varbeta[1 : nparms, 1:nparms]))
)

# This [exp(qnorm...) and 1/qnorm(...)] gives the parameterization used in ppersist (and R base package for Weibull).

# For the other distributions, to translate the parameterizations from 'survival' to ppersist, use:
# exponential:
pdb = exp(betahat) # no scale parameter to worry about

# loglogistic:
pda = 1/betahat[scale parms]
pdb = exp(betahat[other parms]

# lognormal:
pda = betahat[scale parms] ^2
pdb = betahat[other parms]
```

**Comment by DAPPERstats** [comment]
yeah, looks like you figured it out, but the comments are styled with markdown.
you can see what they look like as you type by clicking the "preview" tab next to the "write" tab at the upper left hand side of the box
and setting off code is done with single backticks for inline and three backticks for blocks. alternatively you can click on the <> button in the upper right

**Comment by DAPPERstats** [comment]
ahhhhh thanks for clearing that up re: parameter estimate versus persistence estimate
and thanks much for the code on it!

**Comment by ddalthorp** [comment]
# Correction:
We need to have the second half of the parms in both the "mean = " and the "sd = " for the survreg 'scale' (our 'shape')
```
# for shape (pda):
1/qnorm(1-p,
  mean = cellMM %*% betahat[nparms + 1:nparms],
  sd = sqrt(diag(cellMM %*% varbeta[nparms + 1 : nparms, nparms + 1:nparms]))
)
```

**Comment by DAPPERstats** [comment]
ok, we'll not be using the bootstrap for either `pkm` or `cpm`. the new `cpm` in #77 includes the output on both scales (ppersist and survreg).
