### ISSUE TITLE
Subscript out of bounds

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#93]
I do not know if this is the same issue that Dan identified, but I can also produce an out-of-bounds subscript in the following way: 

1. Load Searcher Efficiency Data File "ExampleSearcherEfficiency.csv"
2. Analysis > General inputs:  Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analysis > Searcher Efficiency:  Observations = **Search4, Search3, Search2, Search1**
                                                      Predictor Variables = Visibility, Fix k = No
4. Run Searcher Efficiency Model

```Listening on http://127.0.0.1:4516
Models with incorrect specification were removed from output.
Warning: Error in [[: subscript out of bounds
Stack trace (innermost first):
    66: observeEventHandler [C:\Users\jmintz\Documents\R\win-library\3.4\GenEst\application\GenEst/server.R#192]
     2: shiny::runApp
     1: GenEst::runGenEst
ERROR: [on_request_read] connection reset by peer
```

You will get similar results if you use Observations not starting with Search1 (only observer 3, observers 2 and 3, etc).

**Comment by DAPPERstats** [comment]
yup, this is a general result if you input the observations in the wrong order. we need to add a check in the base `pkm` function to ensure that the observations are ordered, and to either order them or throw a specific error.

**Comment by DAPPERstats** [comment]
I've included a sort catch that assumes no NAs until you've had a detection and included it for now and that catches the issue. @ddalthorp and @prabie let me know if I need to change that catch

**Comment by ddalthorp** [comment]
"add a check in the base pkm function to ensure that the observations are ordered"

Some requirements (ERROR if not met):
1. only NAs following a 1
2. at most one 1 in a row

Some non-errors:
1. NA between 0s and a 1...but remove the interstitial NAs before feeding data to pkm
2. before removal of interstitial NAs, the number of carcasses per search could well increase with search occasion, but I can't think of a realistic situation where the number would increase _after_ removing the interstitial NAs. However, pkm should work OK regardless. Throw a warning.

**Comment by DAPPERstats** [comment]
what does an NA in the middle of an ordered dataset mean? 

all of the example data provided is structured with NAs after 1s and not between 0s and 1s.

**Comment by mintzj** [comment]
Each "Search" column represents a person's observations, correct?  Could the observations of a searcher be lost, causing an NA representing unknown results?

**Comment by ddalthorp** [comment]
"what does an NA in the middle of an ordered dataset mean?"

It means that the user entered search data by date, and not all carcasses were checked on every date.  This kind of NA is not at all uncommon.

**Comment by ddalthorp** [comment]
...common enough that in the original parsing of data files, we quietly removed those interstitial NAs. 

After a 1, though, there should only be NAs.

**Comment by DAPPERstats** [comment]
that seems like then that there needs to be a pre-processing step before it gets to pkm, then, yeah?

given the meaning of the model, the sequence for any carcass should always be 0s then 1 then NAs.

**Comment by prabie** [comment]
Correct.  This can happen when technicians are excluded from a location due
to maintenance activities or extended periods of snow-cover


* Paul Rabie,  Ph.D*
*Research Biometrician*
*ESA certified Ecologist*

Western Ecosystems Technology, Inc.
Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
307-755-9447
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by DAPPERstats** [comment]
would this be something @mintzj could help with? 
basically, given a proposed realistic data set, if a user picks the observation columns in any order, can we produce an ordered and ready data set?

**Comment by ddalthorp** [comment]
Let's just instruct the user to enter them in order and give ERROR if there are 0s or 1s after an initial 1. The "instruct the user" would be a simple line in the User Guide and part of the ERROR message.

**Comment by mintzj** [comment]
Sure, I can give it a try.  I will chat with Dan a bit to make sure I understand what he is asking for.

**Comment by DAPPERstats** [comment]
these errors are handled through the recent set of PRs (#106 #107 #108 #109 )

i've now got the errors thrown by the base level `pkm` function pulled all the way up through to the app and passed out to the user as red messages, but don't cause breaking

basically, the subscripting errors were the result of failed model fits being represented by singular character elements (a description of the error), but being passed to the analytical code, which expected a highly structured data-filled object. now, there's a catch to not run the analytical code when none of the models fit (previously it would  toss any bad models, but made the implicit assumption at least one model fit successfully)
